### ISSUE TITLE
Errors with latest version of tikz

### ISSUE THREAD

**Issue by dcpurton** [jbezos/colorspace#4]
`colorspace` now gives errors when used with the latest version of `tikz`.

Interestingly, PDF produced still seems OK. At least AcrobatPro does not report any problems and it also separates correctly with GhostScript.

The error occurs with both your master version and with the patches proposed in https://github.com/jbezos/colorspace/pull/2.

# MWE

```TeX
\listfiles
\documentclass{article}
\usepackage{tikz}
\usepackage{colorspace}
\definespotcolor{PANTONE300C}{PANTONE 300 C}{0.99,0.5,0.0,0.0}
\begin{document}
\tikz \fill[PANTONE300C] (0,0) rectangle (1,1);
\end{document}
```

# Error

```
! Undefined control sequence.
\color@&spot ...->\c@lor@arg {#2}\edef #1{\spc@ir 
                                                  \space cs \spc@ir \space C...
l.7 ...z \fill[PANTONE300C] (0,0) rectangle (1,1);
```

# Log and PDF

[colorspace_tikz_bug.log](https://github.com/jbezos/colorspace/files/2998858/colorspace_tikz_bug.log)
[colorspace_tikz_bug.pdf](https://github.com/jbezos/colorspace/files/2998859/colorspace_tikz_bug.pdf)

**Comment by dcpurton** [comment]
As a hint to what is going on, this compiles without error:

```TeX
\documentclass{article}
\usepackage{tikz}
\usepackage{colorspace}
\definespotcolor{PANTONE300C}{PANTONE 300 C}{0.99,0.5,0.0,0.0}
\colorlet{PANTONE300C50}{PANTONE300C!50}
\begin{document}
\tikz \fill[PANTONE300C] (0,0) rectangle (1,1);
\end{document}
```

**Comment by jbezos** [comment]
I've just pushed a new version. Very likely next month I'll submit it (with your pull request) to CTAN, after some tests.
